parameters:
    alerter.class: SymfonyContrib\Bundle\AlerterBundle\AlerterManager
    alerter.form.alert.class: SymfonyContrib\Bundle\AlerterBundle\Form\AlertForm

services:
    alerter.manager:
        class: %alerter.class%
        arguments:
            - %alerter.alerters%
        calls:
            - [setContainer, [@service_container]]

    alerter.form.alert:
        class: %alerter.form.alert.class%
        arguments:
            - %alerter.alerters%
        tags:
            - name: form.type
              alias: alerter_alert_form
